### ISSUE TITLE
error calling cleanup

### ISSUE THREAD

**Issue by bduggan** [CurtTilmes/raku-libcurl#26]
Hi Curt,

When I call `cleanup()`, I get

```
Unknown method clear-form
```

Seems that maybe this method is not being found?

thanks
Brian

**Comment by finanalyst** [comment]
Came across this too. 

I've been using LibCurl::HTTP to check >> 100 http/s links. Somewhere - and this module seems to be a candidate - filehandles are being opened but not closed.

I thought `cleanup`  might help, but the method is unknown.

Using the Comma IDE, the introspection picks up `clearup` as an exported sub for an object of type LibCurl::HTTP.
